// <auto-generated />
using HalcyonApparelsInfrastructure.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalcyonApparelsInfrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230105072407_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AccessoryDetails", b =>
                {
                    b.Property<int>("AccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessoryId"));

                    b.Property<string>("AccessoryBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("AccessoryDiscount")
                        .HasColumnType("INT");

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("AccessoryPrice")
                        .HasColumnType("INT");

                    b.Property<string>("AccessoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessoryId");

                    b.ToTable("AccessoryDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.AdminLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("AdminLogin");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.CustomerDetails", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("ContactId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.LoginCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("LoginCredentials");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.OrderDetails", b =>
                {
                    b.Property<string>("Parent_Order_Id__c")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CustomerDetailsContactId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Product_Type__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ordered_Date__c")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Parent_Order_Id__c");

                    b.HasIndex("CustomerDetailsContactId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.OrderDetails", b =>
                {
                    b.HasOne("HalcyonApparelsDomain.Entities.CustomerDetails", null)
                        .WithMany("orderList")
                        .HasForeignKey("CustomerDetailsContactId");
                });

            modelBuilder.Entity("HalcyonApparelsDomain.Entities.CustomerDetails", b =>
                {
                    b.Navigation("orderList");
                });
#pragma warning restore 612, 618
        }
    }
}
